name: CI/CD
on:
  - push
permissions:
  id-token: write
  contents: read    # This is required for actions/checkout
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret length
        run: echo ${{ secrets.AWS_ROLE }} | awk '{print length}'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
      # - uses: actions/checkout@v2
      # - uses: docker-practice/actions-setup-docker@master
      # - run: docker version
      # - run: docker build -t nginx:latest .
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: nginx
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "image=${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
          # docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          # docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
