name: CI/CD
on:
  - push
permissions:
  id-token: write
  contents: read    # This is required for actions/checkout
jobs:
  aws_auth:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret length
        run: echo ${{ secrets.AWS_ROLE }} | awk '{print length}'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
  build:
    runs-on: ubuntu-latest
    needs:
      - aws_auth
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - run: docker version
      - run: docker build -t nginx:latest .
